export const AGENT_LIMITS = {
	MAX_QUIZZES_PER_RUN: 5,
	MAX_RECOMMENDATIONS_PER_USER_PER_DAY: 3,
	MAX_DAILY_SPEND_USD: parseFloat(process.env.AGENT_MAX_DAILY_SPEND) || 5,
	MIN_CONFIDENCE_AUTO_FLAG: 0.7,
	DUPLICATE_SIMILARITY_THRESHOLD: 0.85,
	PENDING_QUEUE_CAP: 20
};

export const EMBEDDING_CONFIG = {
	MODEL: 'text-embedding-3-small',
	DIMENSIONS: 1536
};
